// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Aw6sInLL-VIb2oYzlS9McLP6aCIVq0U',
    appId: '1:739506266250:web:137fb5ec784a3292aecd73',
    messagingSenderId: '739506266250',
    projectId: 'v-connect-7b8ad',
    authDomain: 'v-connect-7b8ad.firebaseapp.com',
    storageBucket: 'v-connect-7b8ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbilZgGz6DiUOKRVcZ3UQDsili5RFe5Jg',
    appId: '1:739506266250:android:fc6c3ad34ed1c4f1aecd73',
    messagingSenderId: '739506266250',
    projectId: 'v-connect-7b8ad',
    storageBucket: 'v-connect-7b8ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRjAjRplSFxyFIcITFuRTTijgk2m6qQVE',
    appId: '1:739506266250:ios:aa8f013186785b74aecd73',
    messagingSenderId: '739506266250',
    projectId: 'v-connect-7b8ad',
    storageBucket: 'v-connect-7b8ad.appspot.com',
    iosClientId: '739506266250-le9tfb9j30n74mub6s6r9n7viljb78sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.vChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRjAjRplSFxyFIcITFuRTTijgk2m6qQVE',
    appId: '1:739506266250:ios:aa8f013186785b74aecd73',
    messagingSenderId: '739506266250',
    projectId: 'v-connect-7b8ad',
    storageBucket: 'v-connect-7b8ad.appspot.com',
    iosClientId: '739506266250-le9tfb9j30n74mub6s6r9n7viljb78sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.vChat',
  );
}
